spring.application.name=ExpenseTracker
# Server
server.port=8081

# Database (H2 for dev, switch to PostgreSQL for prod)
spring.datasource.url=jdbc:h2:mem:expensedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# --- PostgreSQL (Production) ---
# spring.datasource.url=jdbc:postgresql://localhost:5432/expensedb
# spring.datasource.username=your_user
# spring.datasource.password=your_password
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=jwtsecretKey
jwt.expiration=86400000

# Spring AI (OpenAI)
spring.ai.openai.api-key=apikey
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.chat.options.temperature=0.3
spring.jpa.show-sql=true
logging.level.com.example.expensetracker=DEBUG
logging.level.org.springframework.security=DEBUG